name: imaginotes
description: "Imaginotes app, test for Imaginamos company"
publish_to: 'none'  
version: 1.0.0+1

environment:
  sdk: ^3.7.2
 
dependencies:
  flutter:
    sdk: flutter

  bloc_test: ^10.0.0
  cloud_firestore: ^5.6.5
  cupertino_icons: ^1.0.8
  firebase_analytics: ^11.4.4
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_crashlytics: ^4.3.4
  flutter_bloc: ^9.1.0
  auto_route: ^10.0.1
  either_dart: ^1.0.0
  equatable: ^2.0.7
  get_it: ^8.0.3
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
   
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
 
flutter:
  uses-material-design: true
