// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCppsn_4_14noUbrf5FHjOhyDNea0AxVA',
    appId: '1:116394319461:web:e09936ecd824ad1c59308c',
    messagingSenderId: '116394319461',
    projectId: 'imaginotes-9697a',
    authDomain: 'imaginotes-9697a.firebaseapp.com',
    storageBucket: 'imaginotes-9697a.firebasestorage.app',
    measurementId: 'G-2K0QCLJDNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJCBL7qja9OR86uR7Yrj7VV4Sh2pMjfVw',
    appId: '1:116394319461:android:21fb4db73f41744559308c',
    messagingSenderId: '116394319461',
    projectId: 'imaginotes-9697a',
    storageBucket: 'imaginotes-9697a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKjSMb9N5FmWJ_Nwk1BCMdIkKNXwh_skc',
    appId: '1:116394319461:ios:19aa44f118c08bc259308c',
    messagingSenderId: '116394319461',
    projectId: 'imaginotes-9697a',
    storageBucket: 'imaginotes-9697a.firebasestorage.app',
    iosBundleId: 'com.imaginotes.imaginamos.imaginotes',
  );
}
