// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtnvC7dxHg9RTuIaq7gWduttz7vvuaFhM',
    appId: '1:468104363983:web:c3a31dbb92288a38669cba',
    messagingSenderId: '468104363983',
    projectId: 'imaginotes-fb770',
    authDomain: 'imaginotes-fb770.firebaseapp.com',
    storageBucket: 'imaginotes-fb770.firebasestorage.app',
    measurementId: 'G-Q9EDWHYH13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA2jOeQtvDo47BNOOBr7I0Blk5DmQyBVw',
    appId: '1:468104363983:android:77b8446ed891ff04669cba',
    messagingSenderId: '468104363983',
    projectId: 'imaginotes-fb770',
    storageBucket: 'imaginotes-fb770.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3sbsKJvTHb98o0mkcbdfVc5MLYVoj524',
    appId: '1:468104363983:ios:6f03389e5cb716dc669cba',
    messagingSenderId: '468104363983',
    projectId: 'imaginotes-fb770',
    storageBucket: 'imaginotes-fb770.firebasestorage.app',
    iosBundleId: 'com.imaginotes.imaginamos.imaginotes',
  );

}